name: Deploy to Amazon EC2

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY_2"
          echo "$SSH_PRIVATE_KEY_2" > ~/.ssh/private.pem
          sudo chmod 400 ~/.ssh/private.pem
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/private.pem
        shell: bash
        env:
          SSH_PRIVATE_KEY_2: ${{secrets.SSH_PRIVATE_KEY_2}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
      - name: test connection
        run: |
          ssh ubuntu@3.79.135.33
          pm2 list
