name: Deploy to Amazon EC2

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH key files
        run: |
          mkdir -p ~/.ssh/
          echo "$PRIVATE_KEY_CONTENT" > ~/.ssh/private.pem
          chmod 400 ~/.ssh/private.pem
          echo "$KNOWN_HOSTS_CONTENT" > ~/.ssh/known_hosts
        env:
          PRIVATE_KEY_CONTENT: ${{ secrets.SSH_PRIVATE_KEY }}
          KNOWN_HOSTS_CONTENT: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: SSH into server and run commands
        run: |
          ssh -i ~/.ssh/private.pem ubuntu@3.79.135.33 "pm2 list"