name: Deploy to Amazon EC2

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/private.pem
          sudo chmod 400 ~/.ssh/private.pem
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
      - name: test connection
        run: |
          eval $(ssh-agent -s)
          ssh -i /Users/vincent/.ssh/ec2-key.pem -tt ubuntu@3.79.135.33
          pm2 list
